# Generated by Django 5.1.3 on 2024-12-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(default='YK3qBmz2MhoOxBM8ncwXHFboAqZxPznI', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
