# Generated by Django 5.1.3 on 2024-12-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_profile_verification_token_alter_profile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Suscripción activa'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_trial',
            field=models.BooleanField(default=False, verbose_name='Periodo de prueba'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Correo verificado'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(max_length=32, verbose_name='Token de verificación'),
        ),
    ]
