# Generated by Django 5.1.3 on 2024-12-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_profile_is_subscribed_alter_profile_is_trial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_verified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha verificación'),
        ),
    ]
