# Generated by Django 5.1.3 on 2025-01-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_alter_profile_date_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_birth',
        ),
        migrations.AddField(
            model_name='profile',
            name='adult',
            field=models.BooleanField(default=True, verbose_name='Mayor de edad'),
        ),
    ]
