# Generated by Django 5.1.3 on 2025-01-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_profile_date_verified_update_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified_token_update_email',
            field=models.BooleanField(blank=True, null=True, verbose_name='Correo modificado verificado'),
        ),
    ]
